// apps/front/src/components/landing/GettingStarted.vue
<template>
  <section class="text-white m-auto">
    <div class="p7">
      <h2 class="font-bold mb-5 text-3xl text-center">Готовы начать?</h2>
      <div class="flex flex-row"><TelegramLogo /></div>
    </div>
  </section>
</template>

<script setup lang="ts">
import TelegramLogo from "../../assets/buttons/telegram.svg";
</script>

<style scoped></style>

// frontend/web/src/pages/landing/components/getting-started.tsx
const GettingStarted = () => {
  return (
    <section className="text-white m-auto" id="begin">
      <h2 className="text-white font-bold mb-5 text-4xl text-center">
        Готовы начать?🚀
      </h2>
      <div className="p-7">
        <div className="gap-4 grid grid-cols-1 lg:grid-cols-3 md:grid-cols-2">
          <div className="duration-700 hover:-translate-y-2">
            <div className="bg-[#181818] block drop-shadow-xl rounded">
              <div className="p-6 items-center justify-center flex">
                <img
                  src="./../../../assets/telegram.svg"
                  alt="telegram"
                  width={256}
                  height={256}
                />
              </div>
            </div>
          </div>
          <div className="duration-700 hover:-translate-y-2">
            <div className="bg-[#181818] block drop-shadow-xl rounded">
              <div className="p-6 items-center justify-center flex">
                <img
                  src="./../../../assets/web.svg"
                  alt="web"
                  width={256}
                  height={256}
                />
              </div>
            </div>
          </div>
          <div className="duration-700 hover:-translate-y-2">
            <div className="bg-[#181818] block drop-shadow-xl rounded">
              <div className="p-6 items-center justify-center flex">
                <img
                  src="./../../../assets/phone.svg"
                  alt="phone"
                  width={256}
                  height={256}
                />
              </div>
            </div>
          </div>
          <div className="duration-700 hover:-translate-y-2">
            <div className="bg-[#181818] block drop-shadow-xl rounded">
              <div className="p-6 items-center justify-center flex">
                <img src="./../../../assets/vk.png" alt="vk" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default GettingStarted;
