// apps/rweb/src/pages/landing/components/for-developers.tsx
import React from "react";

const ForDevelopers = () => {
  return (
    <section id="fordevelopers" className="mb-32 mx-6 text-center">
      <div className="p-7">
        <h3 className="text-white font-bold mb-5 text-4xl text-center">
          Разработчикам 🤯
        </h3>
        <p className="font-medium text-lg">
          Мы осознаём важность оставаться открытыми, чтобы позволить проекту
          развиваться. Поэтому это не просто бот, а система представления
          расписания университета в виде нормализованной базы данных. Наша цель
          сделать расписание стабильным и удобным. В этом нам помогают следущие
          технологии:
        </p>
      </div>
    </section>
  );
};

export default ForDevelopers;

// apps/front/src/components/layout/landing/ForDevelopers.vue
<template>
  <section class="flex flex-col h-screen m-auto">
    <div class="p-7">
      <h2 class="text-white font-bold mb-5 text-5xl text-center">
        Разработчикам 🤯
      </h2>
      <p class="font-medium text-lg">
        Мы осознаём важность оставаться открытыми, чтобы позволить проекту
        развиваться. Поэтому это не просто бот, а система представления
        расписания университета в виде нормализованной базы данных. Наша цель
        сделать расписание стабильным и удобным. В этом нам помогают следущие
        технологии:
        
      </p>
    </div>
  </section>
</template>

<script setup lang="ts"></script>

<style scoped></style>
